{{- if .Values.secret.mongoUri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secret.mongoUri | quote }}
  PRIVATE_KEY: {{ .Values.secret.privateKey | quote }}
{{- end }}
